### ISSUE TITLE
Shadowbox: Errors "Unable to resolve"

### ISSUE THREAD

**Issue by Jonybang** [Jigsaw-Code/outline-server#114]
Errors "Unable to resolve" on my hetzner server:

`$ docker logs shadowbox`
Output:
```
D:2018-04-29T10:32:42.540Z] === Config ===
D:2018-04-29T10:32:42.541Z] SB_PUBLIC_IP: 188.40.140.25
D:2018-04-29T10:32:42.541Z] SB_METRICS_URL: https://metrics-prod.uproxy.org
D:2018-04-29T10:32:42.541Z] ==============
I:2018-04-29T10:32:42.589Z] Starting...
I:2018-04-29T10:32:42.661Z] Starting server on port 1292
I:2018-04-29T10:32:42.661Z] starting ss-server with args: -m chacha20-ietf-poly1305 -u --fast-open -p 1292 -k b7WoGpVyyUtZ --manager-address 127.0.0.1:43424
I:2018-04-29T10:32:42.681Z] Starting server on port 62340
I:2018-04-29T10:32:42.681Z] starting ss-server with args: -m chacha20-ietf-poly1305 -u --fast-open -p 62340 -k dvL8opmqvUvw --manager-address 127.0.0.1:43424
I:2018-04-29T10:32:42.843Z] Manager listening at https://[::]:53166/_CZKnC1rgFo8KRc-AQ7F5Q
 2018-04-29 10:32:42 INFO: using tcp fast open
 2018-04-29 10:32:42 INFO: using tcp fast open
 2018-04-29 10:33:42 ERROR: unable to resolve w3.org
E:2018-04-29T10:33:42.754Z] error anonymizing IP address: , Error: ipaddr: the address has neither IPv6 nor IPv4 format
 2018-04-29 10:33:43 ERROR: getpeername: Socket not connected
 2018-04-29 10:33:43 ERROR: getpeername: Socket not connected
 2018-04-29 10:33:43 ERROR: unable to resolve init-p01st.push.apple.com
 2018-04-29 10:33:43 ERROR: unable to resolve www.google.com
```

But internet inside my server and docker container works fine:

`$ docker exec -ti shadowbox /bin/sh`
`~/shadowbox # ping www.google.com`
Output:
```
PING www.google.com (172.217.22.100): 56 data bytes
64 bytes from 172.217.22.100: seq=0 ttl=57 time=5.097 ms
64 bytes from 172.217.22.100: seq=1 ttl=57 time=5.126 ms
64 bytes from 172.217.22.100: seq=2 ttl=57 time=5.126 ms
^C
--- www.google.com ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 5.097/5.116/5.126 ms
```

OS: Ubuntu 16.04
Hosting: Hetzner
Installed via command:
`wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh | bash`
Docker version: 18.04.0-ce, build 3d479c0

What could be the problem?

**Comment by navidlukas** [comment]
Same with me, bump.

**D:2018-05-16T09:00:08.860Z] SB_METRICS_URL: https://metrics-prod.uproxy.org
D:2018-05-16T09:00:08.860Z] ==============
I:2018-05-16T09:00:08.864Z] Starting...
I:2018-05-16T09:00:08.958Z] Starting server on port 17
I:2018-05-16T09:00:08.960Z] starting ss-server with args: -m chacha20-ietf-poly1305 -u --fast-open -p 17 -k fazlUdhtAXfL --manager-address 127.0.0.1:31448
I:2018-05-16T09:00:08.967Z] Starting server on port 33992
I:2018-05-16T09:00:08.967Z] starting ss-server with args: -m chacha20-ietf-poly1305 -u --fast-open -p 33992 -k FSEOrtdjwAtr --manager-address 127.0.0.1:31448
I:2018-05-16T09:00:08.976Z] Starting server on port 22
I:2018-05-16T09:00:08.976Z] starting ss-server with args: -m chacha20-ietf-poly1305 -u --fast-open -p 22 -k BPbXalROCXje --manager-address 127.0.0.1:31448
I:2018-05-16T09:00:09.143Z] Manager listening at https://[::]:42410/kV3bnBjAcRrUvt-nxaf5uQ
 2018-05-16 09:00:08 INFO: using tcp fast open
 2018-05-16 09:00:08 INFO: using tcp fast open
 2018-05-16 09:00:08 INFO: using tcp fast open
E:2018-05-16T09:01:24.025Z] error anonymizing IP address: , Error: ipaddr: the address has neither IPv6 nor IPv4 format
 2018-05-16 09:02:19 ERROR: server recv: Connection reset by peer
 2018-05-16 09:02:19 ERROR: server recv: Connection reset by peer
 2018-05-16 09:02:19 ERROR: server recv: Connection reset by peer
E:2018-05-16T09:02:29.017Z] error anonymizing IP address: , Error: ipaddr: the address has neither IPv6 nor IPv4 format
E:2018-05-16T09:03:04.021Z] error anonymizing IP address: , Error: ipaddr: the address has neither IPv6 nor IPv4 format
**

**Comment by ychw** [comment]
Same here. Everything used to work fine, and one day it stops working. Is anybody looking into this?

`D:2018-06-23T21:26:56.451Z] === Config ===
D:2018-06-23T21:26:56.455Z] SB_PUBLIC_IP: clingmarks.ddns.net
D:2018-06-23T21:26:56.456Z] SB_METRICS_URL: https://metrics-prod.uproxy.org
D:2018-06-23T21:26:56.456Z] ==============
I:2018-06-23T21:26:56.461Z] Starting...
I:2018-06-23T21:26:56.497Z] Starting server on port 53081
I:2018-06-23T21:26:56.497Z] starting ss-server with args: -m chacha20-ietf-poly1305 -u --fast-open -p 53081 -k iSROmBsUGaMr --manager-address 127.0.0.1:12108
I:2018-06-23T21:26:56.510Z] Starting server on port 44142
I:2018-06-23T21:26:56.510Z] starting ss-server with args: -m chacha20-ietf-poly1305 -u --fast-open -p 44142 -k Bdc3iWeSTHTU --manager-address 127.0.0.1:12108
I:2018-06-23T21:26:56.517Z] Starting server on port 55795
I:2018-06-23T21:26:56.517Z] starting ss-server with args: -m chacha20-ietf-poly1305 -u --fast-open -p 55795 -k xcpWcLcaDYWY --manager-address 127.0.0.1:12108
I:2018-06-23T21:26:56.522Z] Starting server on port 15773
I:2018-06-23T21:26:56.523Z] starting ss-server with args: -m chacha20-ietf-poly1305 -u --fast-open -p 15773 -k KYA7xJQw0GHv --manager-address 127.0.0.1:12108
I:2018-06-23T21:26:56.729Z] Manager listening at https://[::]:43222/gvup3IR3Rbxjc-t8ohn0jQ
 2018-06-23 21:26:56 INFO: using tcp fast open
 2018-06-23 21:26:56 INFO: using tcp fast open
 2018-06-23 21:26:56 INFO: using tcp fast open
 2018-06-23 21:26:56 INFO: using tcp fast open
 2018-06-23 21:28:00 ERROR: unable to resolve wikipedia.org
E:2018-06-23T21:28:01.558Z] error anonymizing IP address: , Error: ipaddr: the address has neither IPv6 nor IPv4 format


E:2018-06-23T21:28:06.556Z] error anonymizing IP address: , Error: ipaddr: the address has neither IPv6 nor IPv4 format


 2018-06-23 21:28:12 ERROR: unable to resolve api.getdelta.io
 2018-06-23 21:28:13 ERROR: unable to resolve api.getdelta.io
 2018-06-23 21:28:14 ERROR: unable to resolve api.getdelta.io
 2018-06-23 21:28:14 ERROR: unable to resolve homedepot.sjv.io
 2018-06-23 21:28:14 ERROR: unable to resolve google.com`

**Comment by fortuna** [comment]
I'm sorry for the trouble.

It seems the `unable to resolve` errors are coming from `ss-server`. I believe it uses the system DNS resolver.
Are people still seeing that issue happen? When it happens, does it consistently return errors or does it go back to working normally after some time?

**Comment by fortuna** [comment]
@ychw can you try `dig api.getdelta.io` or `nslookup api.getdelta.io` or the other domains to see if the server is resolving the domains properly?

**Comment by ychw** [comment]
@fortuna yes it works. Here is the output:

```
~$ dig api.getdelta.io

; <<>> DiG 9.8.1-P1 <<>> api.getdelta.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44810
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;api.getdelta.io.		IN	A

;; ANSWER SECTION:
api.getdelta.io.	300	IN	A	104.25.81.97
api.getdelta.io.	300	IN	A	104.25.82.97

;; Query time: 17 msec
;; SERVER: 192.168.2.1#53(192.168.2.1)
;; WHEN: Wed Jul 11 11:50:27 2018
;; MSG SIZE  rcvd: 65
```

**Comment by ychw** [comment]
@fortuna any feedback on this bug?

**Comment by trevj** [comment]
I just merged a PR to include this new version of shadowsocks-libev in Shadowbox:
https://github.com/Jigsaw-Code/outline-server/pull/206

I'll followup here once it's been released (probably early next week).

**Comment by ychw** [comment]
@fortuna @trevj thanks for helping out. But I am not sure it's caused by the version of the shadowsocks-libev. A week ago I actually forked the outline server and upgrade the lib to 3.2.0. But still the same result. You can see the change here: https://github.com/ychw/outline-server/commit/48ed730c14865d9981325cddcfdfaa5f8b59c038

Also, the VPN was working fine for months until one day it suddenly had this problem without any change in system or configuration. It's a little puzzling to me.

**Comment by fortuna** [comment]
@ychw feel free to send those as pull requests in the future :-)
FYI, the new shadowbox with @trevj's fix has been released. Existing servers should start using 3.2.0 automatically.

I'm sorry to hear it may not fix the issue, so we may need further debugging. Is your server hitting 100% CPU or memory?

**Comment by ychw** [comment]
@fortuna @trevj thanks for helping out. The latest version worked fine. 

I do have a separate ask --- the outline app is currently removed from Apple app store. I am trying to build it and send to my friends. However, I don't have access to the certificate repo. Is there a way I can build it and distribute it to my friends?

**Comment by trevj** [comment]
@ychw Delighted to hear it's working for you now!

The server manager isn't in any app store - do you mean the Outline client? I'm afraid in order to (re-)build that for Apple devices you'll need your own developer accounts/certificates/etc.

**Comment by ychw** [comment]
@trevj never mind. I figured out how to build the app with my own account / certificate. 

What I meant was the outline iOS app is removed from China app store.

**Comment by trevj** [comment]
@ychw Glad to hear you were about to build the app.
